### ISSUE TITLE
Create the /Profile Route

### ISSUE THREAD

**Issue by andrew-sequeira** [darenc9/FitFuture#13]
**User Story**
As a user, I would like to view my profile information so that I can update it, and have a personalized experience with my fitness journey.

**Description**
The User Profile Route involves designing and implementing the API route to handle requests related to users profile. This includes defining the endpoint structure and implementing the logic to retrieve user information from the database and return it in a structured format.

**Acceptance Criteria**

- [x] access endpoint to fetch user profile details
- [x] route option to update user profile with user model
- [ ] authentication middleware to ensure only the specific user can access their profile information
- [x] POST route for updating
- [x] GET route for retrieving information

**Testing**

- [x] ensure profile information retrieved is what is expected
- [x] test updating and subsequent retrieving to ensure save occurred
- [ ] accessing endpoint as authorized user
- [ ] accessing endpoint as unauthorized user

**Comment by andrew-sequeira** [comment]
Note: Validation for things like missing input or incorrect format (like number expected but characters are entered) should be done on the UI side

**Comment by mfunkel** [comment]
NOTE: authorization tasks are not completed yet, and will be moved forward to the sprint that implements authorization functionality
