### ISSUE TITLE
Create the /Exercise Route

### ISSUE THREAD

**Issue by andrew-sequeira** [darenc9/FitFuture#16]
**User Story**
As a user, I want to be able to retrieve a list of exercises from the backend API so that I can see the available exercises for my workout routine, and query for exercises.

**Description**
The Exercise Route involves designing and implementing the API route to provide access to a collection of exercises. This includes defining the endpoint structure and implementing the logic to retrieve a list of exercises with additional parameters for retrieving specific exercises or filtering based on type

**Acceptance Criteria**

- [x] ability to `GET` exercise by name
- [x] ability to `GET` all exercises (this should be summary of exercise, name, muscle group targeted, type of exercise, no description)
- [x] ability to `GET` exercises with different filtering parameters
- [x] ability to `GET` exercise by searching for specific name

**Testing**

- [x] JEST tests for GET route, including testing get by id, get all exercises, and filtering parameters

**Comment by darenc9** [comment]
This route is tested by the following UIs and issues:
[Create Exercise Details Page](https://github.com/darenc9/FitFuture/issues/44)
[Create Exercise Selector Page](https://github.com/darenc9/FitFuture/issues/43)
