### ISSUE TITLE
Create Profile Page

### ISSUE THREAD

**Issue by andrew-sequeira** [darenc9/FitFuture#2]
**User story**
As a user, I would like to view my profile information so that I can update it, and have a personalized experience with my fitness journey.

**Description**
The Profile Page involves designing and implementing the user interface for displaying the user's profile information.  This includes creating a dedicated page where users can view and update their personal statistics.  The UI must be implemented such that it will be easy and intuitive to understand and use. The theme must match the other app pages and have a navbar for easy accessibility within the app. The profile page should display all information about the logged in user.

**Acceptance Criteria**
Profile class can hold all relevant information such as the user's name, height, weight, favourite workouts, routines, exercises, workout history, and fitness level.

- [x] Get information on correct user from api call to backend
- [x] Display information in nice format
- [ ] All buttons work as expected
- [x] validation performed on updating profile information
- [x] if updating, POST to api then refresh the profile page with updated information
- [x] capability to navigate to other parts of the workout app
- [x] responsive design to ensure cross device compatibility

**Testing**

- [x] Displaying correct information
- [x] test responsiveness across devices

**Comment by mfunkel** [comment]
NOTE: The "delete profile" button does not prompt for confirmation yet - task will be moved forward to next sprint.
