### ISSUE TITLE
Create Workout Schema

### ISSUE THREAD

**Issue by mfunkel** [darenc9/FitFuture#29]
**User Story**
As a user I would like to be able to browse various preset workouts so that I am able to just follow a specific plan and don't need to research what to do

**Description**
The app should have several preset workouts available for users to execute which should be stored in the database.  The schema for storing the Workout model must be created.  When a user wishes to browse for workouts, or build their own, the workout information should be fetched from / persisted to the database.  The database schema must support and integrate with the Workout model.

**Acceptance Criteria**

- [x] Workouts should be able to be linked to Routines
- [x] Data must be stored accurately
- [x] Data must persist across separate sessions

**Testing**
- [x] verify that schema matches with what is in DB

**Comment by andrew-sequeira** [comment]
Proposed change: remove userId from workout schema -> create new favourites class that would store favouriteId, userid, array of exercise ids, array of workout ids, and array of routine ids

this change will reduce repeated dated in database (initial solution had copies of the same workout with just the userid being different to indicate favourites)

**Comment by andrew-sequeira** [comment]
userId remained in the workout schema for purpose of custom workouts
