### ISSUE TITLE
Populate Database with Preset Workouts

### ISSUE THREAD

**Issue by andrew-sequeira** [darenc9/FitFuture#3]
**User story**
As a user, I would like to have access to a variety of preset workouts to choose from when using the app, so that I can get started without needing to build my own workouts.

**Description**
Preset workouts will have a list of exercises corresponding to a specific type of workout such as cardio, strength training or a specific training day such as lower body push day, upper body pull day etc.  This issue involves manually editing the database to create a variety of workouts that can be used in features such as browsing or during a workout.

**Acceptance Criteria**
User can access and view various preset workouts for all different categories of workouts and for various goals. Should be large number of preset workouts such that user will have enough options based on what they are looking to work out.

- [x] User should be able to read all preset workouts
- [x] preset workouts should be identifiable separately from user-created ones
- [x] should be minimum of 10 preset workouts covering various different muscle groups and workout types

**Testing**

- [x] retrieving specific workout from database should yield correct exercises

**Comment by mfunkel** [comment]
This issue is not linked to a specific PR since it was completed manually (no coding required)
