### ISSUE TITLE
Create WorkoutExercise Schema

### ISSUE THREAD

**Issue by mfunkel** [darenc9/FitFuture#30]
**User Story**
As a user I would like to be able to input my stats for various exercises so that I can keep track of my progress

**Description**
During a workout, the current exercise is displayed for the user to follow - the details of the recommended reps and sets they complete should be displayed.  Once the user is finished with the exercise, they should be able to input their details and that data should be stored for progress tracking and history purposes.  The schema for storing the WorkoutExercise model must be created.  When a user wishes to build a workout or start a workout, information should be fetched from / persisted to the database.  The database schema must support and integrate with the WorkoutExercise model.

**Acceptance Criteria**

- [x] The WorkoutExercise schema must be consistent with the WorkoutExercise model
- [x] Data must be stored accurately
- [x] Data must persist across separate sessions

**Testing**
- [x] verify that schema matches data in DB

**Comment by andrew-sequeira** [comment]
Schema configured and tested. everything appears to work as expected
