### ISSUE TITLE
Create Build Workout Page

### ISSUE THREAD

**Issue by darenc9** [darenc9/FitFuture#40]
**User story**
As a user, I would like to be able to build my own custom workouts and routines so that I can have flexibility and customization for my fitness journey

**Description**
The `Create Build Workout Page` issue involves designing and implementing the frontend page within the app that allows users to create custom workouts This includes an intuitive interface for users to select exercises, specify the sets, reps, duration, and rest intervals, and arrange exercises into a structured workout plan.

**Acceptance Criteria**

- [x] Build Workout page is accessible from the app's navigation menu
- [x] Page must include option to go to exercise selector
- [x] Must include options to specify the sets, reps, durations, and rest intervals for an exercise
- [ ] Interactive feature for users to rearrange the order of exercises, delete exercises from the plan, and adjust parameters as needed
- [x] Must be able to save their workout 

**Testing**

- [x] User can access build workout page
- [x] Can create workout
- [x] Can select and remove exercises within the page
- [x] Can include specific exercise parameters (reps, weights, duration, rest interval)
- [x] Can save a workout into their account

**Comment by andrew-sequeira** [comment]
closed
