### ISSUE TITLE
Create Edit Workout Page

### ISSUE THREAD

**Issue by darenc9** [darenc9/FitFuture#42]
**User story**
User wishes to edit a workout routine, and needs a page where user can load and edit an existing workout.

**Description**
The `Create Edit Workout Page` issue involves designing and implementing the frontend page within the app that allows users to create custom workout routines. This includes showing a list of all existing workouts, and allowing users to load the workout into the workout builder.

**Acceptance Criteria**

- [x] Edit Workout page will be accessible through editing workout on browse page
- [x] Page must include all exercises within that workout
- [x] Sends a workout into the workout builder for users to modify the workout
- [x] ability to add new exercises and delete others

**Testing**

- [x] User can access edit workout page
- [x] Can edit workout
- [x] Can select and remove exercises within the page
- [x] Can include specific exercise parameters (reps, weights, duration, rest interval)
- [x] Can save a workout into their account

**Comment by andrew-sequeira** [comment]
edit page may not be needed, depends on implementation. could just be edit button that re uses the build workout page

**Comment by andrew-sequeira** [comment]
after some though and given back end logic and possible complexity, may make more sense to have a separate edit page

**Comment by andrew-sequeira** [comment]
closed
