### ISSUE TITLE
Profile Schema Updates

### ISSUE THREAD

**Issue by mfunkel** [darenc9/FitFuture#71]
**User Story**
As a user, I would like to update and save my profile information so that I can have a personalized experience with my fitness journey.

**Description**
The Profile Schema Updates issue involves determining which parts of the Profile model's data are considered sensitive information that must be encrypted, and updating the backend to encrypt that data.  Storing sensitive (health) data should follow the appropriate guidelines and legislation, so our app might need to be adjusted to adhere to the appropriate legislation/guidelines.

Note: this is a follow-up issue to #27 

**Acceptance Criteria**

- [ ] Data must be stored securely, with sensitive information encrypted

**Testing**

- [ ] verify that sensitive data is stored securely
- [ ] verify all required profile information is included and can be encrypted/decrypted as needed

**Comment by mfunkel** [comment]
Note: issue closed without task completion - being pushed to Sprint 3

**Comment by RasoulAzwd01** [comment]
> **User Story** As a user, I would like to update and save my profile information so that I can have a personalized experience with my fitness journey.
> 
> **Description** The Profile Schema Updates issue involves determining which parts of the Profile model's data are considered sensitive information that must be encrypted, and updating the backend to encrypt that data. Storing sensitive (health) data should follow the appropriate guidelines and legislation, so our app might need to be adjusted to adhere to the appropriate legislation/guidelines.
> 
> Note: this is a follow-up issue to #27
> 
> **Acceptance Criteria**
> 
> * [ ]  Data must be stored securely, with sensitive information encrypted
> 
> **Testing**
> 
> * [ ]  verify that sensitive data is stored securely
> * [ ]  verify all required profile information is included and can be encrypted/decrypted as needed
